SEO-177725 - React Page with redirect changes
syncfusion-content/ej2-react-docs pull request #284
Opened 2023-11-20 11:31 UTC by Sharly-Atieno

Hi @MallikaRK,

Worked on page with redirect.

Regards,
Sharly A.

2023-11-20 11:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [177725-React-Page-with-Redirect](https://jenkins.syncfusion.com/job/Content/job/ej2-react-docs/193/console)**

2023-11-20 11:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [177725-React-Page-with-Redirect](https://jenkins.syncfusion.com/job/Content/job/ej2-react-docs/193/)<br/>**

2023-11-22 06:22 UTC, Yvone-Atieno requested changes
Commented

2023-11-22 07:18 UTC, Sharly-Atieno commented on ej2-react/treeview/getting-started.md
>  * [How to set tooltip for treeview nodes](./how-to/set-tool-tip-for-tree-nodes/)
updated

2023-11-22 07:18 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [177725-React-Page-with-Redirect](https://jenkins.syncfusion.com/job/Content/job/ej2-react-docs/197/console)**

2023-11-22 07:27 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [177725-React-Page-with-Redirect](https://jenkins.syncfusion.com/job/Content/job/ej2-react-docs/197/)<br/>**

2023-11-23 06:29 UTC, Yvone-Atieno approved these changes
Approved

2023-11-30 14:03 UTC, Aishwarya-Ganesan approved these changes

2023-11-30 14:04 UTC, merged