SEO-177700-Dropped-keywords
syncfusion-content/ej2-react-docs pull request #297
Opened 2023-11-24 15:14 UTC by Edithabich

Hi @gowthamanthavasiyappan ,
Please review the changes.
Thanks.
Regards,
Edith.

2023-11-24 15:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-177700-Dropped-keywords](https://jenkins.syncfusion.com/job/Content/job/ej2-react-docs/212/console)**

2023-11-24 15:18 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-177700-Dropped-keywords](https://jenkins.syncfusion.com/job/Content/job/ej2-react-docs/212/)<br/>**

2023-11-27 10:58 UTC, gowthamanthavasiyappan requested changes
Commented

2023-11-27 10:58 UTC, gowthamanthavasiyappan commented on ej2-react/calendar/getting-started.md
> +description:  Checkout and learn about getting started with Syncfusion Essential React Calendar component, it's elements and more details.
Revert this and remove unwanted space only.

2023-11-27 10:58 UTC, gowthamanthavasiyappan commented on ej2-react/image-editor/getting-started.md
> +description:  Checkout and learn about getting started with Syncfusion Essential React Image Editor component, it's elements and more details.
Revert this, this is ej2 UG page, so the old description is fine.

2023-11-27 10:58 UTC, gowthamanthavasiyappan commented on ej2-react/uploader/getting-started.md
> +description:  Checkout and learn about getting started with Syncfusion Essential React Uploader component, it's elements and more details.
Revert this, check space issue only.

2023-11-27 13:32 UTC, Edithabich commented on ej2-react/uploader/getting-started.md
> +description:  Checkout and learn about getting started with Syncfusion Essential React Uploader component, it's elements and more details.
resolved

2023-11-27 13:51 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-177700-Dropped-keywords](https://jenkins.syncfusion.com/job/Content/job/ej2-react-docs/213/)<br/>**

2024-01-25 11:54 UTC, merged