SEO-177700-React-dropped-keywords-issue-fixes
syncfusion-content/ej2-react-docs pull request #317
Opened 2023-12-07 09:32 UTC by Edithabich

Hi @gowthamanthavasiyappan ,
Please review the changes.
Thanks.
Regards,
Edith.

2023-12-07 09:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-177700-React-dropped-keywords-issue-fixes](https://jenkins.syncfusion.com/job/Content/job/ej2-react-docs/231/console)**

2023-12-07 09:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-177700-React-dropped-keywords-issue-fixes](https://jenkins.syncfusion.com/job/Content/job/ej2-react-docs/231/)<br/>**

2023-12-08 11:30 UTC, gowthamanthavasiyappan requested changes
Commented

2023-12-08 11:30 UTC, gowthamanthavasiyappan commented on ej2-react/heatmap-chart/getting-started.md
> +description:  Checkout and learn about getting started with Syncfusion Essential React HeatMap chart component, it's elements and more details.
Remove unwanted space here

2023-12-08 11:30 UTC, gowthamanthavasiyappan commented on ej2-react/multi-select/getting-started.md
> +description:  Checkout and learn about getting started with Syncfusion Essential React MultiSelect component, it's elements and more details.
Remove unwanted space here

2023-12-19 14:11 UTC, Edithabich commented on ej2-react/multi-select/getting-started.md
> +description:  Checkout and learn about getting started with Syncfusion Essential React MultiSelect component, it's elements and more details.
resolved

2024-01-04 11:48 UTC, gowthamanthavasiyappan approved these changes
Approved

2024-01-25 11:50 UTC, merged