SEO-178943-React-Page-With-Redirect2
syncfusion-content/ej2-react-docs pull request #339
Opened 2024-01-03 12:05 UTC by berylouma

Hello,

I have worked on links with redirects.

Kind Regards,
Beryl.

2024-01-03 12:05 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-178943-React-Page-With-Redirect2](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/4/console)**

2024-01-03 12:12 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-178943-React-Page-With-Redirect2](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/4/console)**

2024-01-03 12:17 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-178943-React-Page-With-Redirect2](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/4/)<br/>**

2024-01-05 09:13 UTC, Yvone-Atieno requested changes
Commented

2024-01-05 09:13 UTC, Yvone-Atieno commented on ej2-react/multi-select/checkbox.md
>  * [How to render grouping with checkbox](./grouping/#grouping-with-checkbox).
Check the above link

2024-01-05 09:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-178943-React-Page-With-Redirect2](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/7/console)**

2024-01-05 09:32 UTC, berylouma commented on ej2-react/multi-select/checkbox.md
>  * [How to render grouping with checkbox](./grouping/#grouping-with-checkbox).
Updated

2024-01-05 09:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-178943-React-Page-With-Redirect2](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/7/)<br/>**

2024-01-05 09:47 UTC, Yvone-Atieno approved these changes
Approved

2024-01-09 11:44 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-178943-React-Page-With-Redirect2](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/8/console)**

2024-01-09 11:45 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-178943-React-Page-With-Redirect2](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/8/console)**

2024-01-09 11:48 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/8/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-01-09 11:49 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-178943-React-Page-With-Redirect2](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/9/console)**

2024-01-09 11:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-178943-React-Page-With-Redirect2](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/9/)<br/>**

2024-01-09 11:58 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-178943-React-Page-With-Redirect2](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/10/console)**

2024-01-09 12:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-178943-React-Page-With-Redirect2](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/10/console)**

2024-01-09 12:08 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-178943-React-Page-With-Redirect2](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/10/)<br/>**

2024-01-10 05:41 UTC, merged