SEO-187689-EJ2-React-Introduction-Page-with-redirect-links
syncfusion-content/ej2-react-docs pull request #510
Opened 2024-08-30 14:35 UTC by Faith-Atieno

Title | Description
-- | --
|Task Category | Coverage Issues|
|Content Task Link/Mail Screenshot | NA|
|Hotfix |https://github.com/syncfusion-content/ej2-documenteditor-react-docs/pull/171|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187689|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B2A368E74-D539-456F-9819-C9B68637E490%7D&file=Faith.xlsx&action=default&mobileredirect=true|

Changes Made | Reason for change |
|-- | -- |
|Changed-Redirect link | To avoid redirect links |

2024-08-30 14:36 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187689-EJ2-React-Introduction-Page-with-redirect-links](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/92/console)**

2024-09-02 09:51 UTC, Yvone-Atieno requested changes
Commented

2024-09-02 09:51 UTC, Yvone-Atieno commented on ej2-react/introduction.md
>          <div class="controlanchorlink"><a target="_self" href="https://ej2.syncfusion.com/react/documentation/breadcrumb/getting-started/">Breadcrumb</a></div>
Check this link

2024-09-02 13:34 UTC, Faith-Atieno commented on ej2-react/introduction.md
>          <div class="controlanchorlink"><a target="_self" href="https://ej2.syncfusion.com/react/documentation/breadcrumb/getting-started/">Breadcrumb</a></div>
resolved

2024-09-02 13:34 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-187689-EJ2-React-Introduction-Page-with-redirect-links](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/94/console)**

2025-01-14 13:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-187689-EJ2-React-Introduction-Page-with-redirect-links](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/158/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/158/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/158/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/158/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/158/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/158/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/158/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/158/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/158/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-react-docs/158/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2025-01-14 13:57 UTC, closed without merging